image:
  repository: ghcr.io/mchenetz/entity
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

namespace:
  create: false

serviceAccount:
  operator: entity-operator
  cosiDriver: entity-cosi-driver

rbac:
  create: true

operator:
  replicaCount: 1
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

objectService:
  create: false
  name: entity
  replicas: 3
  storageClassName: ""
  volumeSize: 100Gi
  serviceType: ClusterIP
  port: 9000
  dataPath: /data
  tlsSecretName: ""
  useCertManager: false
  issuerRefName: ""
  issuerRefKind: Issuer
  issuerRefGroup: cert-manager.io

cosi:
  createClasses: false
  bucketClassName: entity-s3
  bucketAccessClassName: entity-s3-access
  readonly: false
