apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.operator }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.cosiDriver }}
  namespace: {{ .Release.Namespace }}
