apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: pxobj-s3
driverName: pxobj.io/s3
deletionPolicy: Delete
parameters: {}
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccessClass
metadata:
  name: pxobj-s3-access
driverName: pxobj.io/s3
authenticationType: Key
parameters:
  readonly: "false"
