apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: entity-s3
driverName: entity.io/s3
deletionPolicy: Delete
parameters: {}
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccessClass
metadata:
  name: entity-s3-access
driverName: entity.io/s3
authenticationType: Key
parameters:
  readonly: "false"
