{{- if .Values.cosi.createClasses }}
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketClass
metadata:
  name: {{ .Values.cosi.bucketClassName }}
driverName: entity.io/s3
deletionPolicy: Delete
parameters: {}
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccessClass
metadata:
  name: {{ .Values.cosi.bucketAccessClassName }}
driverName: entity.io/s3
authenticationType: Key
parameters:
  readonly: {{ ternary "true" "false" .Values.cosi.readonly | quote }}
{{- end }}
