apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: objectservices.entity.io
spec:
  group: entity.io
  names:
    kind: ObjectService
    listKind: ObjectServiceList
    plural: objectservices
    singular: objectservice
    shortNames:
    - entity
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required: [storageClassName, volumeSize]
            properties:
              replicas:
                type: integer
                minimum: 1
              storageClassName:
                type: string
              volumeSize:
                type: string
              serviceType:
                type: string
              port:
                type: integer
              tlsSecretName:
                type: string
              useCertManager:
                type: boolean
              issuerRefName:
                type: string
              issuerRefKind:
                type: string
              issuerRefGroup:
                type: string
              adminSecretName:
                type: string
              dataPath:
                type: string
              enableVersioning:
                type: boolean
              forcePathStyle:
                type: boolean
          status:
            type: object
            properties:
              phase:
                type: string
              readyReplicas:
                type: integer
              serviceEndpoint:
                type: string
              observedGeneration:
                type: integer
    subresources:
      status: {}
